-- Databricks notebook source
-- Validation 1:Total Revenue by Product category 
-- Question Asked: "What ids the total revenue generated by each product by eacg product category and which category is falling behind?"
-- This query checks which category made the most and least money across al transactions

SELECT 
      `Product Category`,                          --The three product categories
      COUNT(*)    AS Total_Transactions,           -- How many sales per category
      SUM(`Total Amount`) AS Total_Revenue,        --Total money made per category
      ROUND(AVG(`Total Amount`),2) AS Avg_Spend    --Average spend per transaction
FROM retail.sales.dataset
GROUP BY `Product Category`
-- Sort highest revenue first
ORDER BY Total_Revenue DESC;



-- Validation 2:Monthly Revenue Trend for 2023
-- Question Asked: "How does monthly revenue trend across 2023 ,which month performed best and which month should concern the business?"
-- This query shows how much revenue was made each month so  we can spot the best and worst

SELECT
      DATE_FORMAT(Date,'MM')    AS Month_Number,   --Month as a number for sorting  
      DATE_FORMAT(Date,'MMM')   AS Month_Name,     --Month as a name for readability
      COUNT(*)       AS Total_Transactions,        --Number of sales that month
      SUM(`Total Amount`) AS Total_Revenue,        --Total money made that month
      ROUND(AVG(`Total Amount`),2) AS Avg_Spend    --Average spend per transaction
FROM retail.sales.dataset
--Filter to 2023 only ,ignore the single 2024 row
WHERE YEAR(Date) = 2023
GROUP BY Month_Number, Month_Name
--show months in calender order 
ORDER BY Month_Number ASC;

--Validation 3: Age group spending on Each Category
--Question Asked :"Which age group spends the most  on our highest revenue category and which age group are we losing?"
-- This query shows which age group spends the most on each category so we can spot who we are losing

SELECT
--Group customers into life stages 
      CASE
           WHEN Age>= 60 THEN '3. Pensioner(60+)'
           WHEN Age>= 30 THEN '2. Adult(30 - 59)'
           WHEN Age>= 18 THEN '1. Youth(18-29)'
      END                AS Age_Group,
      `Product Category`,            --The product category 
     COUNT(DISTINCT `Customer ID`) AS unique_customers, -- How many different customers
    COUNT(*)                      AS total_transactions, -- Total number of purchases
    SUM(`Total Amount`)           AS total_revenue, -- Total money spent
    ROUND(AVG(`Total Amount`), 2) AS avg_spend      -- Average spend per transaction

FROM retail.sales.dataset

GROUP BY age_group, `Product Category`

-- Show age groups and highest revenue first
ORDER BY age_group, total_revenue DESC;
